#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Mon Apr 17 14:39:02 CEST 2023
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# elaborate design
echo "xelab -wto 4c1eb7f4de1348819b3ae53ba3ca4a56 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot digilent_jstk2_simulation_behav xil_defaultlib.digilent_jstk2_simulation xil_defaultlib.glbl -log elaborate.log"
xelab -wto 4c1eb7f4de1348819b3ae53ba3ca4a56 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot digilent_jstk2_simulation_behav xil_defaultlib.digilent_jstk2_simulation xil_defaultlib.glbl -log elaborate.log

