# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/io.xdc

# Block Designs: bd/space/space.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==space || ORIG_REF_NAME==space} -quiet] -quiet

# IP: bd/space/ip/space_clk_wiz_0_0_1/space_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==space_clk_wiz_0_0 || ORIG_REF_NAME==space_clk_wiz_0_0} -quiet] -quiet

# IP: bd/space/ip/space_AXI4Stream_UART_0_0_1/space_AXI4Stream_UART_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==space_AXI4Stream_UART_0_0 || ORIG_REF_NAME==space_AXI4Stream_UART_0_0} -quiet] -quiet

# IP: bd/space/ip/space_proc_sys_reset_0_0_1/space_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==space_proc_sys_reset_0_0 || ORIG_REF_NAME==space_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/space/ip/space_axi4stream_spi_master_0_0_1/space_axi4stream_spi_master_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==space_axi4stream_spi_master_0_0 || ORIG_REF_NAME==space_axi4stream_spi_master_0_0} -quiet] -quiet

# IP: bd/space/ip/space_digilent_jstk2_0_0_1/space_digilent_jstk2_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==space_digilent_jstk2_0_0 || ORIG_REF_NAME==space_digilent_jstk2_0_0} -quiet] -quiet

# IP: bd/space/ip/space_jstk_uart_bridge_0_0_1/space_jstk_uart_bridge_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==space_jstk_uart_bridge_0_0 || ORIG_REF_NAME==space_jstk_uart_bridge_0_0} -quiet] -quiet

# XDC: /home/matteo/Scrivania/UNI/Digital Electronics System Design/spaceship/spaceship.gen/sources_1/bd/space/space_ooc.xdc
