# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/pins.xdc

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_0_0 || ORIG_REF_NAME==design_1_clk_wiz_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_proc_sys_reset_0_0/design_1_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_proc_sys_reset_0_0 || ORIG_REF_NAME==design_1_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_proc_sys_reset_0_1/design_1_proc_sys_reset_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_proc_sys_reset_0_1 || ORIG_REF_NAME==design_1_proc_sys_reset_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_dual_i2s_0_0/design_1_axis_dual_i2s_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axis_dual_i2s_0_0 || ORIG_REF_NAME==design_1_axis_dual_i2s_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi4stream_spi_master_0_0/design_1_axi4stream_spi_master_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi4stream_spi_master_0_0 || ORIG_REF_NAME==design_1_axi4stream_spi_master_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_digilent_jstk2_0_0/design_1_digilent_jstk2_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_digilent_jstk2_0_0 || ORIG_REF_NAME==design_1_digilent_jstk2_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_debouncer_3_0/design_1_debouncer_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_debouncer_3_0 || ORIG_REF_NAME==design_1_debouncer_3_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_edge_detector_2_0/design_1_edge_detector_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_edge_detector_2_0 || ORIG_REF_NAME==design_1_edge_detector_2_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_edge_detector_2_1/design_1_edge_detector_2_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_edge_detector_2_1 || ORIG_REF_NAME==design_1_edge_detector_2_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_led_controller_1_0/design_1_led_controller_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_led_controller_1_0 || ORIG_REF_NAME==design_1_led_controller_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_debouncer_2_0/design_1_debouncer_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_debouncer_2_0 || ORIG_REF_NAME==design_1_debouncer_2_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_dual_moving_average_0_0/design_1_dual_moving_average_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_dual_moving_average_0_0 || ORIG_REF_NAME==design_1_dual_moving_average_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_mute_1_0/design_1_mute_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_mute_1_0 || ORIG_REF_NAME==design_1_mute_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_balance_controller_0_0/design_1_balance_controller_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_balance_controller_0_0 || ORIG_REF_NAME==design_1_balance_controller_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_volume_0_0/design_1_volume_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_volume_0_0 || ORIG_REF_NAME==design_1_volume_0_0} -quiet] -quiet

# XDC: /home/fede/Desktop/Polimi/DesdProject/Lab3/lab3/lab3.gen/sources_1/bd/design_1/design_1_ooc.xdc
