#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Thu Mar 30 21:26:55 CEST 2023
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# elaborate design
echo "xelab -wto 26be7ebe3bb44bc4a136e9a5711c6269 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot TestKittCar_behav xil_defaultlib.TestKittCar -log elaborate.log"
xelab -wto 26be7ebe3bb44bc4a136e9a5711c6269 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot TestKittCar_behav xil_defaultlib.TestKittCar -log elaborate.log

